name = "gitlfs-worker"
main = "src/index.ts"
compatibility_date = "2024-12-21"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "OBJECT_STORE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


[[r2_buckets]]
binding = "LFS_BUCKET"
bucket_name = "gitlfs-bucket"

[[durable_objects.bindings]]
name = "LOCK"
class_name = "Lock"
